import type { RoleCatalogEntry, RoleId } from "./types";

/**
 * Mechanical role definitions (Two Rooms and a Boom).
 * Display names live in theme.ts so the flock theme can change without touching IDs.
 */
export const ROLE_CATALOG: Record<RoleId, RoleCatalogEntry> = {
  president: {
    id: "president",
    team: "blue",
    primary: true,
    filler: false,
    minPlayers: 6,
    canonicalName: "President",
  },
  bomber: {
    id: "bomber",
    team: "red",
    primary: true,
    filler: false,
    minPlayers: 6,
    canonicalName: "Bomber",
  },
  blue_team: {
    id: "blue_team",
    team: "blue",
    primary: false,
    filler: true,
    minPlayers: 6,
    canonicalName: "Blue Team",
  },
  red_team: {
    id: "red_team",
    team: "red",
    primary: false,
    filler: true,
    minPlayers: 6,
    canonicalName: "Red Team",
  },
  gambler: {
    id: "gambler",
    team: "grey",
    primary: false,
    filler: false,
    minPlayers: 6,
    canonicalName: "Gambler",
  },
  mi6: {
    id: "mi6",
    team: "grey",
    primary: false,
    filler: false,
    minPlayers: 12,
    canonicalName: "MI6",
  },
  doctor: {
    id: "doctor",
    team: "blue",
    primary: false,
    filler: false,
    minPlayers: 11,
    pairWith: "engineer",
    canonicalName: "Doctor",
  },
  engineer: {
    id: "engineer",
    team: "red",
    primary: false,
    filler: false,
    minPlayers: 11,
    pairWith: "doctor",
    canonicalName: "Engineer",
  },
  coy_blue: {
    id: "coy_blue",
    team: "blue",
    primary: false,
    filler: false,
    minPlayers: 11,
    pairWith: "coy_red",
    canonicalName: "Coy Boy",
  },
  coy_red: {
    id: "coy_red",
    team: "red",
    primary: false,
    filler: false,
    minPlayers: 11,
    pairWith: "coy_blue",
    canonicalName: "Coy Boy",
  },
  spy_blue: {
    id: "spy_blue",
    team: "blue",
    primary: false,
    filler: false,
    minPlayers: 11,
    pairWith: "spy_red",
    canonicalName: "Spy",
  },
  spy_red: {
    id: "spy_red",
    team: "red",
    primary: false,
    filler: false,
    minPlayers: 11,
    pairWith: "spy_blue",
    canonicalName: "Spy",
  },
  negotiator_blue: {
    id: "negotiator_blue",
    team: "blue",
    primary: false,
    filler: false,
    minPlayers: 11,
    pairWith: "negotiator_red",
    canonicalName: "Negotiator",
  },
  negotiator_red: {
    id: "negotiator_red",
    team: "red",
    primary: false,
    filler: false,
    minPlayers: 11,
    pairWith: "negotiator_blue",
    canonicalName: "Negotiator",
  },
  werewolf_a: {
    id: "werewolf_a",
    team: "grey",
    primary: false,
    filler: false,
    minPlayers: 12,
    pairWith: "werewolf_b",
    canonicalName: "Werewolf",
  },
  werewolf_b: {
    id: "werewolf_b",
    team: "grey",
    primary: false,
    filler: false,
    minPlayers: 12,
    pairWith: "werewolf_a",
    canonicalName: "Werewolf",
  },
  survivor: {
    id: "survivor",
    team: "grey",
    primary: false,
    filler: false,
    minPlayers: 12,
    canonicalName: "Survivor",
  },
  victim: {
    id: "victim",
    team: "grey",
    primary: false,
    filler: false,
    minPlayers: 12,
    canonicalName: "Victim",
  },
  intern: {
    id: "intern",
    team: "grey",
    primary: false,
    filler: false,
    minPlayers: 12,
    canonicalName: "Intern",
  },
  rival: {
    id: "rival",
    team: "grey",
    primary: false,
    filler: false,
    minPlayers: 12,
    canonicalName: "Rival",
  },
  angel_blue: {
    id: "angel_blue",
    team: "blue",
    primary: false,
    filler: false,
    minPlayers: 16,
    pairWith: "angel_red",
    canonicalName: "Angel",
  },
  angel_red: {
    id: "angel_red",
    team: "red",
    primary: false,
    filler: false,
    minPlayers: 16,
    pairWith: "angel_blue",
    canonicalName: "Angel",
  },
  mime_blue: {
    id: "mime_blue",
    team: "blue",
    primary: false,
    filler: false,
    minPlayers: 18,
    pairWith: "mime_red",
    canonicalName: "Mime",
  },
  mime_red: {
    id: "mime_red",
    team: "red",
    primary: false,
    filler: false,
    minPlayers: 18,
    pairWith: "mime_blue",
    canonicalName: "Mime",
  },
  paparazzo_blue: {
    id: "paparazzo_blue",
    team: "blue",
    primary: false,
    filler: false,
    minPlayers: 20,
    pairWith: "paparazzo_red",
    canonicalName: "Paparazzo",
  },
  paparazzo_red: {
    id: "paparazzo_red",
    team: "red",
    primary: false,
    filler: false,
    minPlayers: 20,
    pairWith: "paparazzo_blue",
    canonicalName: "Paparazzo",
  },
};

export const ALL_ROLE_IDS = Object.keys(ROLE_CATALOG) as RoleId[];

export function getRole(id: RoleId): RoleCatalogEntry {
  return ROLE_CATALOG[id];
}
